name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-minify-plugin mkdocstrings-python  mkdocs-material mkdocstrings
      - run: mkdocs gh-deploy --force --clean --verbose